# Generated by Django 2.1.2 on 2021-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210302_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Avatar.jpg', upload_to='profile_pics'),
        ),
    ]
